### ISSUE TITLE
Cannot delete Players imported from DiceCloud

### ISSUE THREAD

**Issue by JukeBoxHeroTP** [cynicaloptimist/improved-initiative#180] opened 2018-02-11 19:54 UTC
This character, which I imported from DiceCloud, will not go away. I click the delete button, the confirmation appears, I click "OK", and then nothing happens. It is still there after refreshing.

Additionally, when I go edit this character's stat block and remove almost everything from it, and then save, everything I deleted reappears when I refresh.

Here is the json of the character I am having this issue with:
[Anra Lifiri.txt](https://github.com/cynicaloptimist/improved-initiative/files/1714776/Anra.Lifiri.txt)

**Comment by cynicaloptimist** [comment] 2018-02-12 04:27
Dupe of #154

**Closed by cynicaloptimist** 2018-02-12 04:27 UTC
