### ISSUE TITLE
Epic Initiative settings for DM view

### ISSUE THREAD

**Issue by Dan503** [cynicaloptimist/improved-initiative#473] opened 2020-02-02 02:55 UTC
I just signed up for epic initiative but none of the settings under the epic initiative tab seem to work.

I turned on inline portraits, still don't see inline portraits.

I changed every setting, even added some custom CSS but still didn't see any change in the interface.

Refreshing the page didn't apply any changes either.

**Comment by cynicaloptimist** [comment] 2020-02-02 03:24
Try relaunching the Player View. Let me know if that doesn't work.

**Comment by Dan503** [comment] 2020-02-02 03:35
This is in the DM view, I haven't tested in the player view.

Closing and opening the browser, clearing cache, loging out and logging back in. None of these sorts of things work.

**Comment by cynicaloptimist** [comment] 2020-02-02 04:40
Those features only work in the Player View. Sorry for the confusion!

**Comment by Dan503** [comment] 2020-02-02 04:41
Can you consider this a feature request to port them over to the DM view?

It's more important for the DM to be able to see these UI differences than the players in my opinion.

**Comment by cynicaloptimist** [comment] 2020-02-02 07:10
Not currently planned, but it's not a bad idea. Custom CSS might be an issue because the DM view tends to change frequently enough that Custom CSS for it would break frequently.

**Comment by Dan503** [comment] 2020-02-02 07:32
Leaving out custom CSS is fine.

I wanted to be able to see the character portraits in the list view as a DM to help me think about who is up next and what the upcoming enemies should do on their turns. it's easier to do that with a visual reference.

Being able to make the active party member stand out more in the list through custom styling settings also helps the DM keep track of things more easily.

**Comment by Dan503** [comment] 2020-02-02 11:53
Hi, I'm taking a look into doing the fix myself and submitting a pull request.

I'm already stuck though.

I ran `npm ci` to get the install. That worked.

I ran `npm run build-dev`. That worked.

Then I ran `npm run start` but no browser window auto-opened and there was no message saying "seved on localhost:3000" or something. How do I view the development version of the site?

Also, I added my name to the `thanks.ts` file so I wouldn't forget to do it later, saved the file then tried to commit but then I got this error message:

```
> improved-initiative@2.11.7 lint C:\Users\danie\Projects\forked-projects\improved-initiative
> eslint --fix '**/**/*.{ts,tsx}'


Oops! Something went wrong! :(

ESLint: 6.8.0.

No files matching the pattern "'**/**/*.{ts,tsx}'" were found.
Please check for typing mistakes in the pattern.
```

I'm running Windows 10, Node v10.17.0

**Comment by cynicaloptimist** [comment] 2020-02-02 23:08
Thanks for the interest in contributing! 

The browser won't auto-open to the app.
_From readme.md:_
> Once the Improved Initiative app is running, the ui can be accessed at http://localhost

Not sure why ESLint is failing. There's a pre-commit hook that tries to run eslint against open files. I noticed your listed Node version isn't up to the recommended version in package.json, but I doubt that is the issue.  If all else fails, try running the commit for that file with the --no-verify flag

BTW, make sure you take a look at this incoming PR #471 - the Tracker view initiative list is totally reimplemented in React, which would affect implementation of this.

**Comment by Dan503** [comment] 2020-02-03 00:38
Is PR #471 likely to get merged soonish?

I would much rather work with React than whatever is currently being used for the DM view.

**Comment by cynicaloptimist** [comment] 2020-02-03 00:56
It's merged now, hack away!

**Comment by Dan503** [comment] 2020-02-03 11:22
I managed to get git-commits working!

I needed to change the `"lint"` command under `"scripts"` to this:

```
"lint": "eslint --fix **/*.{ts,tsx}"
```

The main difference is that I removed the quote marks around `**/*.{ts,tsx}`. Can you check that the above lint command works for you?

**Comment by Dan503** [comment] 2020-02-03 12:33
This project is starting to turn into more trouble than it's worth 😖

I read through the readme now.

I ran all the commands. I can't get an environment up and running that allows me to view my changes though.

`npx grunt` doesn't seem to boot up a localhost server. `npm run start` boots up the server ok but it doesn't seem to render the current state of the code-base.

I tried running both `npx grunt` and `npm run start` in 2 seperate console windows and I still can't get any changes to appear on `localhost` 😥

**Comment by cynicaloptimist** [comment] 2020-02-04 04:45
Sorry about the frustration getting the project running! I'd note that reading the README.md is generally the _first_ thing you should do. If you follow those instructions exactly, you should be all set. Since you're interested in contributing, I also recommend reading CONTRIBUTING.md.

`grunt` indeed does not run the server; it just does the build and watches the files to rebuild when TS files change. You should see the console running grunt update when you save any .ts or .tsx file. `npm start` runs the server. They're separate commands because my normal workflow involves running the server under the VS Code debugger. If you're running in development mode, then any changes to the client code should be visible after you refresh.

Not sure how much of your difficulty is caused by factors in your dev environment. Other contributors haven't reported issues like yours, and the app deploys itself to CI and Heroku with minimal configuration. I just tested a clean clone, install, build, and server launch in a bare Powershell window and was able to access the ui at http://localhost/

Feel free to provide screenshots of the exact issues you're running into, I'm happy to help troubleshoot. Thanks!

**Comment by Dan503** [comment] 2020-02-04 07:48
Ok, so pressing `F5` to get the server running and running `npx grunt` in a seperate console window worked. I can finally start working now 🤗

I think I'll update the readme as part of my pull request to stop people getting as lost as I was.

**Comment by Dan503** [comment] 2020-02-04 07:50
Just wondering, do we need to support IE11?

I'm mainly asking for the sake of using CSS Grid for styling instead of Flexbox.

**Comment by cynicaloptimist** [comment] 2020-02-17 08:01
Merged PR, closing issue

**Closed by cynicaloptimist** 2020-02-17 08:01 UTC
Labels: enhancement, help wanted

**Comment by Dan503** [comment] 2020-02-17 08:18
_Technically_ the pull request didn't fully meet the requirements of this issue. The issue states that all the epic initiative features should be provided to the DM view.

The main reason I opened this issue though was to get the character portraits into the DM screen. The PR completes that requirement though so I'm fine with this issue being closed. I got what i wanted. 😊
