### ISSUE TITLE
Spell linking incorrectly when spell starts with "Shield" in Creature traits

### ISSUE THREAD

**Issue by Atobers** [cynicaloptimist/improved-initiative#221] opened 2018-05-03 00:15 UTC
When adding the spell "Shield of Faith" to the spell list and then adding it to the spell list of a creature, it only links the first word of "Shield" to the "Shield" spell in the SRD.

However, this behavior does not seem to repeat itself on other spells that are similar. For example, if you have the spells:
Wall of Fire, Wall of Force, Wall of Ice, Wall of Stone, Wall of Thorns
and a test spell called "Wall". Spells will correctly link to their respective spells.

![shield](https://user-images.githubusercontent.com/38928226/39555209-5cbf8f5e-4e2c-11e8-827a-f755023f7b50.PNG)

**Comment by cynicaloptimist** [comment] 2018-05-03 01:35
Excellent find, thanks for the bug. I'll have a fix for this out on the next release.

**Comment by paulmoliva** [comment] 2019-09-05 21:08
@cynicaloptimist 
![image](https://user-images.githubusercontent.com/14105031/64380812-c62da100-cfff-11e9-9807-a9100a10e2c4.png)

This seems to still happen. Point me to the right file and I will make a PR to fix it.

**Comment by cynicaloptimist** [comment] 2019-09-06 03:49
The SpellsByNameRegex is responsible for this:
https://github.com/cynicaloptimist/improved-initiative/blob/development/client/Library/SpellLibrary.ts#L14

concatenatedStringRegex sorts the strings by name, which was the original fix for this issue:
https://github.com/cynicaloptimist/improved-initiative/blob/development/common/Toolbox.ts#L27

If you'd like to make changes to the concatenatedStringRegex method, please include a test for it.

Thanks!

**Comment by cynicaloptimist** [comment] 2019-09-20 06:14
I misunderstood the earlier comment. The example with the Hobgoblin is by design, since there's no reliable way to disambiguate the *shield* spell from an actual physical shield.

**Closed by cynicaloptimist** 2019-09-20 06:14 UTC
Labels: bug
