### ISSUE TITLE
[Bug] Some Spells are not parsed in the creature text

### ISSUE THREAD

**Issue by AntonioOne** [cynicaloptimist/improved-initiative#483] opened 2020-02-27 22:54 UTC
I added some spells from Xanatar and EEPC for creatures that use them. But some of them are not converted into links in the text (though some are). Examples are:  Absorb Elements, Tidal Wave, Frostbite, Thunderclap.

**Comment by AntonioOne** [comment] 2020-02-27 22:57
Examples of ones that worked fine: Charm Monster, Shape Water, Maelstorm.

**Comment by coreyjkelly** [comment] 2020-03-01 22:22
Did you import those spells as well? You can include them in your JSON file when you import the creatures. They're not in the OGL, so they're not included with Improved Initiative by default.

**Comment by cynicaloptimist** [comment] 2020-04-09 03:47
Couldn't reproduce this issue, closing.

**Closed by cynicaloptimist** 2020-04-09 03:47 UTC
